export const {
  REACT_APP_FIREBASE_BASE_URL,
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGE_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID,
  REACT_APP_MEASUREMENT_ID,
  REACT_APP_FIRE_BASE_USER_EMAIL,
  REACT_APP_FIRE_BASE_USER_PASSWORD,
} = process.env;
